foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = 'recipes.views.page_not_found'
handler500 = 'recipes.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),

    # регистрация и авторизация
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    path('api/v1/', include('api_v1.urls')),

    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('technology/', views.flatpage,
         {'url': '/technology/'}, name='technology'),

    path('', include('recipes.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('recipe/new/', views.new_recipe, name='new_recipe'),
    path('recipe/<slug:slug>-<int:recipe_id>/',
         views.view_recipe, name='recipe'),
    path('recipe/<slug:slug>-<int:recipe_id>/edit/',
         views.edit_recipe, name='edit_recipe'),
    path('recipe/<slug:slug>-<int:recipe_id>/delete/',
         views.delete_recipe, name='delete_recipe'),

    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('favorites/', views.favorites, name='favorites'),
    path('purchases/', views.purchases, name='purchases'),
    path('purchases/download/', views.purchases_to_pdf, name='download'),
    path('<username>/', views.profile, name='profile'),
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

recipes/models.py
import ast

from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

User = get_user_model()


# поле для хранения данных в формате списка
class ListField(models.CharField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def from_db_value(self, value, expression, connection):
        if value is None:
            return value
        if isinstance(value, str):
            return value.split(',')

    def to_python(self, value):
        if not value:
            value = []
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            return ast.literal_eval(value)

    def get_prep_value(self, value):
        if value is None:
            return value
        if value is not None and isinstance(value, str):
            return value
        if isinstance(value, list):
            return ','.join(value)

    def value_to_string(self, obj):
        value = self.value_from_object(obj)
        return self.get_prep_value(value)


class Product(models.Model):
    title = models.CharField('Название', max_length=200, db_index=True)
    dimension = models.CharField('Еденицы измерения', max_length=20)

    def __str__(self):
        return f'{self.title} {self.dimension}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Recipe(models.Model):
    TAGS_CHOICES = (
        ('breakfast', 'Завтрак'),
        ('lunch', 'Обед'),
        ('dinner', 'Ужин'),
    )

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Автор',
        related_name='recipes')
    title = models.CharField('Название рецепта', max_length=200)
    slug = models.SlugField(unique=False, max_length=200, db_index=True)
    tags = ListField('Теги', max_length=200)
    time = models.PositiveIntegerField(
        'Время приготовления',
        validators=[MinValueValidator(1), MaxValueValidator(999)])
    description = models.TextField('Описание')
    image = models.ImageField('Фото', upload_to='recipes/')
    pub_date = models.DateTimeField(
        'Дата публикации', auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    name = models.CharField('Название', max_length=200)
    value = models.FloatField(
        'Количество',
        validators=[MinValueValidator(0), MaxValueValidator(9999)])
    units = models.CharField('Единицы измерения', max_length=20)
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name='Рецепт',
        related_name='ingredients')

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return f'{self.name}'


class Favorite(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Пользователь',
        related_name='favorites')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name='Рецепт',
        related_name='favorites')

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'


class Subscription(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Пользователь',
        related_name='subscriptions')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Автор',
        related_name='subscribers')

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class Purchase(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Пользователь',
        related_name='purchases')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name='Рецепт',
        related_name='purchases')

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'

recipes/forms.py
import posixpath

from django import forms
from django.conf import settings
from django.utils.safestring import mark_safe

from .models import Ingredient, Recipe


# виджет для отображения кнопки добавления изображения
class ImageWidget(forms.widgets.ClearableFileInput):
    template_name = 'widgets/image_file_input.html'


class RecipeForm(forms.ModelForm):
    tags = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Recipe
        fields = ('title', 'description', 'image', 'time', 'tags')
        labels = {
            'title': 'Название рецепта',
            'description': 'Описание',
            'image': 'Загрузить фото',
            'time': 'Время приготовления',
        }
        widgets = {
            'description': forms.Textarea(attrs={
                'rows': 8,
            }),
            'image': ImageWidget
        }

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)

        self.fields['breakfast'] = forms.BooleanField(
            required=False, initial='breakfast' in self.instance.tags)
        self.fields['lunch'] = forms.BooleanField(
            required=False, initial='lunch' in self.instance.tags)
        self.fields['dinner'] = forms.BooleanField(
            required=False, initial='dinner' in self.instance.tags)

        for field_name in self.data:
            if (
                field_name.startswith('nameIngredient_')
                or field_name.startswith('unitsIngredient_')
            ):
                self.fields[field_name] = forms.CharField(
                    required=False, widget=forms.HiddenInput())
            if (field_name.startswith('valueIngredient_')):
                self.fields[field_name] = forms.FloatField(
                    required=False, widget=forms.HiddenInput())

    def clean(self):
        cleaned_data = super(RecipeForm, self).clean()
        cleaned_data['tags'] = self.get_tags()
        cleaned_data['ingredients'] = self.get_ingredients(
            cleaned_data)
        if not cleaned_data['ingredients']:
            self.add_error(None, 'Добавьте ингредиенты')
        if not cleaned_data['tags']:
            self.add_error('tags', 'Добавьте тег')
        return cleaned_data

    def add_ingredients(self):
        recipe = self.instance
        recipe.ingredients.all().delete()
        for ingredient in self.cleaned_data['ingredients']:
            Ingredient.objects.create(
                recipe=recipe,
                name=ingredient['name'],
                value=ingredient['value'],
                units=ingredient['units'],
            )

    def get_ingredients(self, data):
        ingredients = list()
        for key in dict(data.items()):
            if 'nameIngredient' in key:
                ingredient_num = key.split('_')[1]
                ingredient = {
                    'id': ingredient_num,
                    'name': data[f'nameIngredient_{ingredient_num}'],
                    'value': data[f'valueIngredient_{ingredient_num}'],
                    'units': data[f'unitsIngredient_{ingredient_num}']
                }
                ingredients.append(ingredient)
        return ingredients

    def get_ingredient_fields(self):
        ingredients = self.get_ingredients(self.data)

        if not self.errors:
            ingredients += list(Ingredient.objects.filter(recipe=self.instance)
                                .values())

        for ingredient in ingredients:
            yield ingredient

    def get_tags(self):
        tags = list()

        if 'breakfast' in dict(self.data.items()):
            tags.append('breakfast')
        if 'lunch' in dict(self.data.items()):
            tags.append('lunch')
        if 'dinner' in dict(self.data.items()):
            tags.append('dinner')

        return tags

recipes/views.py
import io
from datetime import datetime

import reportlab
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from .forms import RecipeForm
from .models import Favorite, Ingredient, Recipe, Subscription
from .utils import get_filter_tags, slugify

User = get_user_model()


def index(request):
    recipe_list = Recipe.objects.order_by('-pub_date').all()
    recipe_list = recipe_list.filter(get_filter_tags(request))

    # показывать по 6 рецептов на странице
    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    data = {
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'index.html', context=data)


def profile(request, username):
    subscription = False
    profile = get_object_or_404(User, username=username)

    recipe_list = Recipe.objects.filter(author=profile).order_by('-pub_date')
    recipe_list = recipe_list.filter(get_filter_tags(request))

    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    if request.user.is_authenticated:
        subscription = Subscription.objects.filter(
            user=request.user, author=profile).first()

    data = {
        'profile': profile,
        'page': page,
        'paginator': paginator,
        'subscription': subscription,
    }
    return render(request, 'profile.html', context=data)


def view_recipe(request, slug, recipe_id):
    subscription = False
    favorite = False

    recipe = get_object_or_404(Recipe, id=recipe_id, slug=slug,)

    if request.user.is_authenticated:
        subscription = Subscription.objects.filter(
            user=request.user, author=recipe.author).first()

        favorite = Favorite.objects.filter(
            user=request.user, recipe=recipe).first()

    data = {
        'recipe': recipe,
        'subscription': subscription,
        'favorite': favorite,
    }
    return render(request, 'recipe.html', context=data)


@login_required
def new_recipe(request):
    if request.method == 'POST':

        form = RecipeForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.slug = slugify(recipe.title)
            recipe.save()
            form.add_ingredients()
            return redirect('index')

        return render(request, 'new_recipe.html', {'form': form})

    form = RecipeForm()
    return render(request, 'new_recipe.html', {'form': form, })


@login_required
def edit_recipe(request, slug, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id, slug=slug)

    if recipe.author != request.user:
        return redirect('recipe', slug=recipe.slug, recipe_id=recipe_id)
    form = RecipeForm(request.POST or None,
                      files=request.FILES or None, instance=recipe)

    if request.method == 'POST':
        if form.is_valid():
            recipe.save()
            form.add_ingredients()
            return redirect('recipe', slug=recipe.slug, recipe_id=recipe_id)

    return render(request, 'new_recipe.html', {'form': form, 'recipe': recipe})


@login_required
def delete_recipe(request, slug, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id, slug=slug)
    if recipe.author != request.user:
        return redirect('recipe', slug=recipe.slug, recipe_id=recipe_id)

    recipe.delete()

    return redirect('index')


@login_required
def subscriptions(request):
    profile = get_object_or_404(User, username=request.user)
    subscription_list = profile.subscriptions.all()

    paginator = Paginator(subscription_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    data = {
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'subscriptions.html', context=data)


@login_required
def favorites(request):
    profile = request.user

    favorites = profile.favorites.all().values('recipe')
    recipe_list = Recipe.objects.filter(pk__in=favorites).order_by('-pub_date')
    recipe_list = recipe_list.filter(get_filter_tags(request))

    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    data = {
        'page': page,
        'paginator': paginator
    }
    return render(request, 'favorites.html', context=data)


def purchases(request):
    if request.user.is_authenticated:
        profile = request.user
        recipes_list = Recipe.objects.filter(
            pk__in=profile.purchases.values('recipe')
        )
    else:
        request.session.setdefault('purchases', [])
        recipes_list = Recipe.objects.filter(
            pk__in=request.session['purchases']
        )

    data = {
        'recipes': recipes_list,
    }
    return render(request, 'purchases.html', context=data)


# формирование PDF документа со списком покупок
def purchases_to_pdf(request):
    today = datetime.today().strftime('%d-%m-%Y')

    if request.user.is_authenticated:
        profile = request.user
        ingredients = Ingredient.objects.filter(
            recipe__in=profile.purchases.values('recipe')
        ).values('name', 'units').annotate(Sum('value')).order_by('name')
    else:
        ingredients = Ingredient.objects.filter(
            recipe__in=request.session['purchases']
        ).values('name', 'units').annotate(Sum('value')).order_by('name')

    buffer = io.BytesIO()

    reportlab.rl_config.TTFSearchPath.append(
        str(settings.BASE_DIR) + '/static/fonts')
    pdfmetrics.registerFont(TTFont('Arial', 'arial.ttf'))
    p = canvas.Canvas(buffer, pagesize=A4)
    p.setFont('Arial', 16, leading=None)
    p.drawString(10 * mm, 277 * mm, 'Список покупок')
    p.line(10 * mm, 272 * mm, 200 * mm, 272 * mm)

    y = 267 * mm
    for i, item in enumerate(ingredients, 1):
        p.setFont('Arial', 14, leading=None)
        p.drawString(
            20 * mm, y - 5 * mm,
            f'{i}. {item["name"]} - {item["value__sum"]} {item["units"]}')
        y = y - 8 * mm

    p.line(10 * mm, 10 * mm, 200 * mm, 10 * mm)
    p.setFont('Arial', 10, leading=None)
    p.drawString(10 * mm, 5 * mm, today)
    p.drawRightString(200 * mm, 5 * mm, 'Продуктовый помощник')

    p.setTitle(f'Список покупок от {today}')
    p.showPage()
    p.save()

    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True,
                        filename='Список покупок.pdf')


# вывод страницы при ошибке 404
def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


# вывод страницы при ошибке 500
def server_error(request):
    return render(request, 'misc/500.html', status=500)

recipes/templates/author_item.html
{% load recipe_filters %}

<div class="card-user" data-author="{{ author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">
            <a href="{% url 'profile' author.username %}" class="card-user__title link">
                {{ author.get_full_name }}
            </a>
        </h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in author.recipes.all|slice:":3" %}
            {% include 'author_recipe_item.html' with recipe=recipe %}
            {% endfor %}

            {% with author.recipes.count|add:-3 as total %}
            {% if total > 0 %}
            <li class="card-user__item">
                <a href="{% url 'profile' author.username %}" class="card-user__link link">
                    Еще {{ total }} {{ total|rupluralize:"рецепт,рецепта,рецептов" }}...
                </a>
            </li>
            {% endif %}
            {% endwith %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">
            Отписаться
        </button>
    </div>
</div>

recipes/templates/author_recipe_item.html
<li class="card-user__item">
    <div class="recipe">
        {% load thumbnail %}
        {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
        <img class="recipe__image" src="{{ im.url }}" alt="{{ recipe.title }}" />
        {% endthumbnail %}
        <h3 class="recipe__title"><a class="recipe__title link" href="{% url 'recipe' recipe.slug recipe.id %}"
                target="_blank">{{ recipe.title }}</a></h3>
        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
    </div>
</li>

recipes/templates/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Избранное{% endblock %}

{% block nav %}
{% include 'nav.html' with favorites=True %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/pages/index.css' %}">
{% endblock %}

{% block scripts_js %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
{% endif %}

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/pages/favorite.js' %}"></script>
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Избранное</h1>
    <!-- Вывод фильтра по тегам -->
    {% include 'tag_filter.html' with breakfast=breakfast lunch=lunch dinner=dinner%}
</div>
<div class="card-list">
    {% for recipe in page %}
    {% include 'recipe_item.html' with recipe=recipe %}
    {% empty %}
    <h3 class="card__title">Тут пока пусто...</h3>
    {% endfor %}
</div>

<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
{% include 'paginator.html' with items=page paginator=paginator%}
{% endif %}

{% endblock %}

recipes/templates/new_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if form.instance.pk is None %}Создание рецепта{% else %}Редактирование рецепта{% endif %}
{% endblock %}

{% block nav %}
{% include 'nav.html' with new_recipe=True %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/pages/form.css' %}">
{% endblock %}

{% block scripts_js %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/pages/formRecipe.js' %}"></script>
<script type="text/javascript">
    document.getElementById('id_image').onchange = function () {
        var file = this.value;
        file = file.replace(/\\/g, '/').split('/').pop();
        document.getElementById('image__name').innerHTML = file;
    }
</script>
{% endblock %}

{% block content %}
{% load recipe_filters %}

<div class="main__header">
    <h1 class="main__title">
        {% if form.instance.pk is None %}Создание рецепта{% else %}Редактирование рецепта{% endif %}
    </h1>
</div>
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form__group">
            <label for="id_name" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                {{ form.title|addclass:'form__input' }}
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                <div class="tags">
                    <div class="tags__item">
                        {{ form.breakfast|addclass:'tags__checkbox tags__checkbox_style_orange' }}
                        <label for="id_breakfast" class="tags__label">Завтрак</label>
                    </div>
                    <div class="tags__item">
                        {{ form.lunch|addclass:'tags__checkbox tags__checkbox_style_green' }}
                        <label for="id_lunch" class="tags__label">Обед</label>
                    </div>
                    <div class="tags__item">
                        {{ form.dinner|addclass:'tags__checkbox tags__checkbox_style_purple' }}
                        <label for="id_dinner" class="tags__label">Ужин</label>
                    </div>
                </div>
                {{ form.tags }}
                {% for error in form.tags.errors %}
                <span class="form__error">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0">
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% for item in form.get_ingredient_fields %}
                    <div class="form__field-item-ingredient" id="ing_{{ item.id }}">
                        <span> {{ item.name }} - {{ item.value|floatformat:'-2' }}
                            {{ item.units }}</span> <span class="form__field-item-delete"></span>
                        <input id="nameIngredient_{{ item.id }}" name="nameIngredient_{{ item.id }}" type="hidden"
                            value="{{ item.name }}">
                        <input id="valueIngredient_{{ item.id }}" name="valueIngredient_{{ item.id }}" type="hidden"
                            value="{{ item.value|format_float }}">
                        <input id="unitsIngredient_{{ item.id }}" name="unitsIngredient_{{ item.id }}" type="hidden"
                            value="{{ item.units }}">
                    </div>
                    {% endfor %}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                {% for error in form.non_field_errors %}
                <span class="form__error">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form__group">
            <label for="id_time" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                {{ form.time|addclass:'form__input' }}
                <label for="id_time" class="form__label">минут</label>
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_description" class="form__label">Описание</label>
            <div class="form__field-group">
                {{ form.description|addclass:'form__textarea'|safe }}
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                {{ form.image|addclass:'form__file' }}
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__footer">
            <button class="button button_style_blue">
                {% if form.instance.pk is None %}Создать рецепт{% else %}Сохранить{% endif %}
            </button>
            {% if form.instance.pk %}
            <a style="margin-left: 2.5em" href="{% url 'delete_recipe' recipe.slug recipe.id %}"
                class="form__ingredient-link">Удалить</a>
            {% endif %}
        </div>
    </form>
</div>

{% endblock %}

recipes/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Рецепты{% endblock %}

{% block nav %}
{% include 'nav.html' with index=True %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/pages/index.css' %}">
{% endblock %}

{% block scripts_js %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
{% endif %}

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/pages/authorRecipe.js' %}"></script>
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">
        {% if profile.get_full_name %}
        {{ profile.get_full_name }}
        {% else %}
        {{ profile.username }}
        {% endif %}
    </h1>
    <!-- Вывод фильтра по тегам -->
    {% include 'tag_filter.html' with breakfast=breakfast lunch=lunch dinner=dinner%}
</div>

{% if profile != user and user.is_authenticated %}
<div class="author-subscribe" data-author="{{ profile.id }}">
    {% if subscription %}
    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe"
            name="subscribe">Отписаться от автора</button></p>
    {% else %}
    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe"
            data-out>Подписаться на автора</button></p>
    {% endif %}
</div>
{% endif %}

<div class="card-list">
    {% for recipe in page %}
    {% include 'recipe_item.html' with recipe=recipe %}
    {% empty %}
    <h3 class="card__title">Тут пока пусто...</h3>
    {% endfor %}
</div>

<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
{% include 'paginator.html' with items=page paginator=paginator%}
{% endif %}

{% endblock %}

recipes/templates/purchases.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список покупок{% endblock %}

{% block nav %}
{% include 'nav.html' with purchases=True %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/pages/shopList.css' %}">
{% endblock %}

{% block scripts_js %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/pages/shopList.js' %}"></script>
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Список покупок</h1>
</div>
<div class="card-list card-list_column">
    <ul class="shopping-list">
        {% for recipe in recipes %}
        <li class="shopping-list__item" data-id="{{ recipe.id }}">
            <div class="recipe recipe_reverse">
                {% load thumbnail %}
                {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                <img class="recipe__image recipe__image_big" src="{{ im.url }}" alt="{{ recipe.title }}" />
                {% endthumbnail %}
                <h3 class="recipe__title">
                    <a class="recipe__title link" href="{% url 'recipe' recipe.slug recipe.id %}" target="_blank">
                        {{ recipe.title }}
                    </a>
                </h3>
                <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
            </div>
            <button class="shopping-list__button button button_style_none">Удалить</button>
        </li>
        {% empty %}
        <h3 class="recipe__title">Тут пока пусто...</h3>
        {% endfor %}
    </ul>

    {% if recipes %}
    <a href="{% url 'download' %}">
        <button class="button button_style_blue">Скачать список</button>
    </a>
    {% endif %}
</div>
{% endblock %}